config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'home/index'
  get 'home/show'
  root to: "posts#index"
  resources :posts do
    resources :comments
  end
  resources :favorites, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show]

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
  validates :message, presence: true
  mount_uploader :image, PostImageUploader
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def show
    @comments = @post.comments
    @comment = @post.coment.build
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def create
    @comment = @post.comments.build(comment_params) 
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to post_path(@post), notice: '投稿できませんでした...' }
      end
    end
  end

  def update
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :index }
      else
        format.js { render :errors }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) 
    if @comment.destroy
      render :index 
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:image, :message, :user_id, :post_id, :image_cache)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end
end

app/views/comments/_edit.html.erb
<div>
<%= form_with(model: [@post, @comment]) do |form| %>
    <p id="error-message"></p>

    <div class="field">
        <%= form.label :comment %>
        <%= form.text_area :message, class: "input", id: "edit_comment" %>
    </div>

    <div class="actions">
        <%= form.submit "編集する", class: "button is-info" %>
    </div>
<% end %>



<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>
</div>

app/views/comments/_errors.html.erb
<div class "errors">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2> <%= pluralize(@comment.errors.count, "error") %>エラーがあります。</h2>
      <ul>
      <% @comment.errors.full_messages.each dp |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment] ) do |form| %>
  <div>
    <%= form.text_area :message, class: "input" %>
  </div>
  <div class="field">
  <%= form.label :image %>
  <%#= form.image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする" %>
  </div>
  <br><br><br>
<% end %>

app/views/comments/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>

  <tbody>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <p><%= link_to "#{comment.user.username}さん", user_path(comment.user.id) %></p>
      <p>コメント：<%= comment.message %></p>
      <div class="comment_image">
      <% if comment.image.present? %>
        <%= image_tag comment.image.to_s %>
      <% end %>
      <% if comment.user == current_user %>
        <p><%= link_to 'コメントを編集する', edit_post_comment_path(comment.post, comment), remote: true %></p>
        <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true %></p>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

<p id="comment"></p>
<p id="error-message"></p>

app/views/comments/edit.js.erb
$('#comment').html("<%= j(render(partial: '/comments/edit')) %>");

app/views/comments/errors.js.erb
$('#error-message').html("<%= j(render(partial: '/comments/errors')) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @comment.image %>
</p>

<p>
  <%= @comment.message %>
</p>

<p>
  <%= @comment.user_id %>
</p>

<p>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>