config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'home/index'
  get 'home/show'
  root to: "posts#index"
  resources :posts do
    resources :comments
  end
  resources :favorites, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show]

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, PostImageUploader
  validates :youtube_url, length: { maximum: 255 }
  validates :content, presence: true
  # validates :youtube_url, length: { is: 11 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result
    
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @comment = Comment.new 
    @comments = @post.comments 
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
    
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :image, :youtube_url)
    end

    def search_params
      params.require(:q).permit(:content_cont)
    end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <h5>Youtube urlにはyoutubeのURLを入れてください</h5>
  <div class="field">
    <%= form.label :youtube_url %>
    <%= form.text_field :youtube_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<br><br>
<%= link_to 'Show', @post, class: 'btn btn-default' %> |
<%= link_to 'Back', posts_path, class: 'btn btn-default' %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <theader>
  <%= search_form_for @q do |f| %>
    <%= f.search_field :content_cont, id: "search_bar" %>
    <%= f.submit "検索" %>
  <% end %>
  </theader>
  <h1>Posts</h1>
  <tbody>
    <% @posts.each do |post| %>
      <div class="user_info">
      <h4><div class="user_icon">
        <%= link_to(user_path(post.user.id)) do %>
        <% unless post.user.image.blank? %>
          <%= image_tag post.user.image.to_s%>
          <% else %>
          <%= image_tag("non-image.jpg") %>
        <% end %>
      <% end %>
          <%= post.user.username %></h4>
        </div>
      </div>
      <hr>
      <div class="post_youtube_url">
      <% unless post.youtube_url.blank? %>
        <div><iframe width="560" height="315" src="https://www.youtube.com/embed/<%=post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
      <% end %>
      <br><br>
      <div class="post_contents">
        <%= post.content %>
        </div>
        <br><br>
        <div class="post_image">
        <% unless post.image.blank? %>
          <%= image_tag post.image.to_s %>
        <% end %>
        </div>
      </div>
      <br>
        <p id="show_button"><%= link_to t('post.Show'), post, class: 'btn btn-default' %></p>
        <% if post.user_id == current_user.id %>
          <%= link_to t('post.Edit'), edit_post_path(post), class: 'btn btn-default' %>
          <%= link_to t('post.Destroy'), post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        <% end %>
        <div id="favorite_button"><% if post.user_id != current_user.id %>
          <% if current_user.favorites.find_by(post_id: post.id).present? %>
            <%= link_to 'お気に入り解除する', favorite_path(id: post.id), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'お気に入りする', favorites_path(post_id: post.id), method: :post, class: 'btn btn-primary' %>
          <% end %>
        <% end %></div>
        <br><hr><br>
    <hr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<br><br>
<%= link_to 'Back', posts_path, class: 'btn btn-default' %>

app/views/posts/show.html.erb
<div class="show_container">
  <p id="notice"><%= notice %></p>

  <div class="user_info">
    <div class="user_icon">
    <% if @post.user.image.present? %>
    <%= image_tag @post.user.image.to_s %>
    <% else %>
      <%= image_tag("non-image.jpg") %>
    <% end %>
    </div>
    <%= @post.user.username %>
  </div>
  <hr>
  <p>
    <div class="post_youtube_url">
      <% unless @post.youtube_url.blank? %>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%=@post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
      <hr>
      <%= @post.content %><br>
      <% unless @post.image.blank? %>
      <%= image_tag @post.image.to_s %>
      <% end %>
    </div>
  </p>
  <hr>

  <h4>コメント</h4>

  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, post: @post  } %>
  </div>  
  <% if user_signed_in? %>
    <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
  <% end %>
  </div>
  <% if @post.user_id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-default' %>
  <% end %>
  <%= link_to 'Back', posts_path, class: 'btn btn-default' %>
</div>