config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'home/index'
  get 'home/show'
  root to: "posts#index"
  resources :posts do
    resources :comments
  end
  resources :favorites, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show]

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VIDEOMania</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="wrapper">
    <app_header>
      <nav>
      <%= link_to(root_path) do %>
        <%= image_tag 'VIDEOMANIA_logo.png', class: 'Videomania_logo' %>
      <% end %>
        <% if user_signed_in? %> 
          <%= link_to '　  Home  　', posts_path, class: 'btn btn-default' %> 
          <%= link_to '   My Page   ', user_path(current_user), class: 'btn btn-default' %> 
          <%= link_to '   New Post   ', new_post_path, class: 'btn btn-default' %> 
        <p class="navbar-text navbar-right"><%= link_to "ログアウト", sign_out_path, id: "logout", class: 'btn btn-default' %></p>
        <% else %>
          <%= link_to "サインイン", new_user_registration_path, class: 'btn btn-default' %> 
          <%= link_to "ログイン", new_user_session_path, class: 'btn btn-default' %>
        <% end %>
      </nav>

    </app_header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <div class="container">
      <%= yield %>
      </div>
      <footer>
        <p>@VIDEO_MANIA</p>
      </footer>
    </div>
  </body>
</html>